spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

app.seed.enabled=false

spring.jpa.open-in-view=false
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=0

server.tomcat.threads.max=25
spring.jpa.properties.hibernate.default_batch_fetch_size=16

springdoc.swagger-ui.enabled=false
springdoc.api-docs.enabled=false
